name: bonsoir_linux
description: Linux implementation of the Bonsoir plugin.
homepage: https://bonsoir.skyost.eu
repository: https://github.com/Skyost/Bonsoir/tree/main/packages/bonsoir_linux
issue_tracker: https://github.com/Skyost/Bonsoir/issues
version: 6.0.2
publish_to: none

environment:
  sdk: ">=3.11.0 <4.0.0"
  flutter: ">=3.41.0"

flutter:
  plugin:
    implements: bonsoir
    platforms:
      linux:
        dartPluginClass: BonsoirLinux

dependencies:
  flutter:
    sdk: flutter
  bonsoir_platform_interface:
    git: https://github.com/kumsumit/bonsoir_platform_interface.git
  dbus:
    git: https://github.com/kumsumit/dbus.dart.git
  meta: ^1.17.0

dev_dependencies:
  flutter_lints: ^6.0.0
